In [1]:
import os
print(os.getcwd())

/content

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# 2. 현재 작업 디렉토리를 'model' 폴더로 변경
# 'KOPIS 공모전' 폴더가 내 드라이브 바로 아래에 있다고 가정합니다.
os.chdir('/content/drive/MyDrive/KOPIS 공모전/model')

# 현재 작업 디렉토리 확인 (이제 'model' 폴더가 되어야 합니다)
print(os.getcwd())

/content/drive/MyDrive/KOPIS 공모전/model

In [4]:
import pandas as pd

# 이제 상대 경로가 올바르게 작동합니다.
# '../'는 'model'의 상위 폴더인 'KOPIS 공모전'을 의미합니다.
file_path = '../data/except_complex.csv'

try:
    df = pd.read_csv(file_path)
    print("데이터를 성공적으로 불러왔습니다. 🎉")
    print(df.head())
except FileNotFoundError:
    print(f"오류: '{file_path}' 경로에 파일이 없습니다. 경로를 다시 확인해주세요.")

데이터를 성공적으로 불러왔습니다. 🎉
            공연명       장르명     세부장르명                                출연진내용  \
0          보디가드       뮤지컬       뮤지컬   김선영, 박기영, 손승연, 해나, 이동건, 강경준, 최현선 등
1     인어공주 [구미]       뮤지컬       뮤지컬    김우현, 김효경, 김두현, 박동혁, 문지우, 손치현, 박소민
2   허클베리피: 분신 9      대중음악      대중가요                                  NaN
3  절대 변하지 않는 것들  한국음악(국악)        기악              안은경, 전우석, 김기중, 장경희, 임용주
4       난타 [명동]       뮤지컬  넌버벌 퍼포먼스  손석배, 유승수, 황요한, 김문수, 김대호, 조기철, 이한범 등

             제작진내용                            기획제작사명 원작자명 극작가명
0  박소영, 박지훈, 김준태 등                    (주)CJ ENM(제작사)  NaN  NaN
1  손지현, 김현주, 박신호 등       극단 레미.레오(기획사), 극단 레미.레오(주최)  NaN  NaN
2              NaN  (주)하이라이트레코즈(주최), (주)하이라이트레코즈(주관)  NaN  NaN
3  류형선, 정우연, 최경현 등                               NaN  NaN  NaN
4              송승환   (주)피엠씨프러덕션(PMC Production)(제작사)  NaN  NaN

In [5]:
df.head()

,공연명,장르명,세부장르명,출연진내용,제작진내용,기획제작사명,원작자명,극작가명
0,보디가드,뮤지컬,뮤지컬,"김선영, 박기영, 손승연, 해나, 이동건, 강경준, 최현선 등","박소영, 박지훈, 김준태 등",(주)CJ ENM(제작사),NaN,NaN
1,인어공주 [구미],뮤지컬,뮤지컬,"김우현, 김효경, 김두현, 박동혁, 문지우, 손치현, 박소민","손지현, 김현주, 박신호 등","극단 레미.레오(기획사), 극단 레미.레오(주최)",NaN,NaN
2,허클베리피: 분신 9,대중음악,대중가요,NaN,NaN,"(주)하이라이트레코즈(주최), (주)하이라이트레코즈(주관)",NaN,NaN
3,절대 변하지 않는 것들,한국음악(국악),기악,"안은경, 전우석, 김기중, 장경희, 임용주","류형선, 정우연, 최경현 등",NaN,NaN,NaN
4,난타 [명동],뮤지컬,넌버벌 퍼포먼스,"손석배, 유승수, 황요한, 김문수, 김대호, 조기철, 이한범 등",송승환,(주)피엠씨프러덕션(PMC Production)(제작사),NaN,NaN

In [6]:
file_path_2 = '../data/complex.csv'

try:
    df_complex = pd.read_csv(file_path_2)
    print("데이터를 성공적으로 불러왔습니다. 🎉")
    print(df_complex.head())
except FileNotFoundError:
    print(f"오류: '{file_path_2}' 경로에 파일이 없습니다. 경로를 다시 확인해주세요.")

데이터를 성공적으로 불러왔습니다. 🎉
                공연명 장르명   세부장르명                               출연진내용  \
0       인더스트리얼 퍼포먼스  복합  다원/융복합                            예효승, 나혜영
1        아웃 오브 더 블루  복합      복합  신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등
2             이색콘서트  복합      복합                                 김진철
3             슬픔의 집  복합  다원/융복합                                 NaN
4  차세대열전, 이어지음 프로젝트  복합      복합                  강인아, 고석진, 조의선, 최태훈

             제작진내용                                      기획제작사명 원작자명  극작가명
0              NaN                                    금은보화(주관)  NaN   NaN
1              류경한  SY Ent(에스와이 이엔티)(주관), 김지연 아코디언 팝스오케스트라(주최)  NaN   NaN
2              NaN                 (주)지앤미디어(주최), (주)지앤미디어(기획사)  NaN   NaN
3  김지선, 강윤지, 문기강 등                                         NaN  NaN   NaN
4  강안나, 강한별, 최세린 등                               한국문화예술위원회(주최)  NaN   NaN

In [7]:
df_complex.head()

,공연명,장르명,세부장르명,출연진내용,제작진내용,기획제작사명,원작자명,극작가명
0,인더스트리얼 퍼포먼스,복합,다원/융복합,"예효승, 나혜영",NaN,금은보화(주관),NaN,NaN
1,아웃 오브 더 블루,복합,복합,"신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등",류경한,"SY Ent(에스와이 이엔티)(주관), 김지연 아코디언 팝스오케스트라(주최)",NaN,NaN
2,이색콘서트,복합,복합,김진철,NaN,"(주)지앤미디어(주최), (주)지앤미디어(기획사)",NaN,NaN
3,슬픔의 집,복합,다원/융복합,NaN,"김지선, 강윤지, 문기강 등",NaN,NaN,NaN
4,"차세대열전, 이어지음 프로젝트",복합,복합,"강인아, 고석진, 조의선, 최태훈","강안나, 강한별, 최세린 등",한국문화예술위원회(주최),NaN,NaN

In [8]:
import re
import pandas as pd

# 제거할 패턴 (문자열 끝에 오는 '등', '외', '外')
def clean_tail_words(item):
    return re.sub(r"(등|외|外)$", "", item).strip()

def split_and_clean(x):
    if pd.isna(x):
        return []
    items = [i.strip() for i in str(x).split(",") if i.strip()]

    clean_items = []
    for item in items:
        # 괄호 안 내용 제거
        item = re.sub(r"\(.*?\)", "", item).strip()
        # 끝에 붙은 '등', '외', '外' 제거
        item = clean_tail_words(item)
        if len(item) > 0:
            clean_items.append(item)
    return clean_items

In [9]:
def standardize_names(name_list):
    """
    출연진/제작진 이름 리스트에서 괄호 안 내용 및 불필요한 문자 제거 후 표준화
    """
    if not isinstance(name_list, list):
        return []
    cleaned_names = []
    for name in name_list:
        # 괄호 안 내용 제거
        name = re.sub(r"\(.*?\)", "", name).strip()
        # 끝에 붙은 '등', '외', '外' 제거 (clean_tail_words 함수 재활용)
        name = clean_tail_words(name)
        if len(name) > 0:
            cleaned_names.append(name)
    return cleaned_names

# '출연진내용' 컬럼에 split_and_clean 함수를 적용하여 리스트 형태로 만든 후 표준화 (df 데이터프레임)
df['출연진내용_list'] = df['출연진내용'].apply(split_and_clean)
df['출연진내용_standardized'] = df['출연진내용_list'].apply(standardize_names)

# '출연진내용'과 '제작진내용' 컬럼에 split_and_clean 함수를 적용하여 리스트 형태로 만든 후 표준화 (df_complex 데이터프레임)
df_complex['출연진내용_list'] = df_complex['출연진내용'].apply(split_and_clean)
df_complex['제작진내용_list'] = df_complex['제작진내용'].apply(split_and_clean)

df_complex['출연진내용_standardized'] = df_complex['출연진내용_list'].apply(standardize_names)
df_complex['제작진내용_standardized'] = df_complex['제작진내용_list'].apply(standardize_names)

print("df 데이터프레임 출연진 표준화 결과:")
display(df[['출연진내용', '출연진내용_list', '출연진내용_standardized']].head())

print("\ndf_complex 데이터프레임 출연진 및 제작진 표준화 결과:")
display(df_complex[['출연진내용', '출연진내용_list', '출연진내용_standardized', '제작진내용', '제작진내용_list', '제작진내용_standardized']].head())

df 데이터프레임 출연진 표준화 결과:

,출연진내용,출연진내용_list,출연진내용_standardized
0,"김선영, 박기영, 손승연, 해나, 이동건, 강경준, 최현선 등","[김선영, 박기영, 손승연, 해나, 이동건, 강경준, 최현선]","[김선영, 박기영, 손승연, 해나, 이동건, 강경준, 최현선]"
1,"김우현, 김효경, 김두현, 박동혁, 문지우, 손치현, 박소민","[김우현, 김효경, 김두현, 박동혁, 문지우, 손치현, 박소민]","[김우현, 김효경, 김두현, 박동혁, 문지우, 손치현, 박소민]"
2,NaN,[],[]
3,"안은경, 전우석, 김기중, 장경희, 임용주","[안은경, 전우석, 김기중, 장경희, 임용주]","[안은경, 전우석, 김기중, 장경희, 임용주]"
4,"손석배, 유승수, 황요한, 김문수, 김대호, 조기철, 이한범 등","[손석배, 유승수, 황요한, 김문수, 김대호, 조기철, 이한범]","[손석배, 유승수, 황요한, 김문수, 김대호, 조기철, 이한범]"

df_complex 데이터프레임 출연진 및 제작진 표준화 결과:

,출연진내용,출연진내용_list,출연진내용_standardized,제작진내용,제작진내용_list,제작진내용_standardized
0,"예효승, 나혜영","[예효승, 나혜영]","[예효승, 나혜영]",NaN,[],[]
1,"신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등","[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]","[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",류경한,[류경한],[류경한]
2,김진철,[김진철],[김진철],NaN,[],[]
3,NaN,[],[],"김지선, 강윤지, 문기강 등","[김지선, 강윤지, 문기강]","[김지선, 강윤지, 문기강]"
4,"강인아, 고석진, 조의선, 최태훈","[강인아, 고석진, 조의선, 최태훈]","[강인아, 고석진, 조의선, 최태훈]","강안나, 강한별, 최세린 등","[강안나, 강한별, 최세린]","[강안나, 강한별, 최세린]"

### 데이터셋 구축 및 GNN 모델 준비
- 출연진과 제작진 이름 표준화 -> GNN 모델 학습에 필요한 **그래프 데이터셋 구축**해야함

In [10]:
# 1. 통합 노드 및 엣지 리스트 생성

# 인물/기관 노드 리스트: df와 df_complex의 출연진내용_standardized와 제작진내용_standardized 컬럼의 모든 이름을 모아서 중복을 제거합니다.
all_personnel_names = set()
for name_list in df['출연진내용_standardized']:
    all_personnel_names.update(name_list)
for name_list in df_complex['출연진내용_standardized']:
    all_personnel_names.update(name_list)
for name_list in df_complex['제작진내용_standardized']:
    all_personnel_names.update(name_list)

personnel_nodes = sorted(list(all_personnel_names))
print(f"총 인물/기관 노드 수: {len(personnel_nodes)}")
# print("인물/기관 노드 예시:", personnel_nodes[:10]) # 너무 많을 수 있으니 일부만 출력


# 공연 노드 리스트: 모든 공연의 고유 ID(index 또는 공연명)를 공연 노드로 사용합니다.
# 여기서는 데이터프레임의 index를 공연 ID로 사용하겠습니다.
# df와 df_complex의 인덱스를 합쳐서 사용
all_performance_indices = list(df.index) + list(df_complex.index)
performance_nodes = sorted(list(set(all_performance_indices))) # 혹시 모를 중복 제거 및 정렬
print(f"총 공연 노드 수: {len(performance_nodes)}")
# print("공연 노드 예시:", performance_nodes[:10])


# 장르 노드 리스트: df에서 '장르명'에 있는 모든 단일 장르를 장르 노드로 정의합니다.
genre_nodes = sorted(list(df['장르명'].unique()))
print(f"총 장르 노드 수: {len(genre_nodes)}")
print("장르 노드 리스트:", genre_nodes)


# 노드 타입별 ID 매핑 딕셔너리 생성
# GNN 라이브러리에서 노드를 정수 ID로 관리하기 때문에 매핑이 필요합니다.
# 인물/기관 노드는 0부터 시작, 공연 노드는 인물/기관 노드 수부터 시작, 장르 노드는 공연 노드 수 + 인물/기관 노드 수부터 시작
personnel_id_map = {name: i for i, name in enumerate(personnel_nodes)}
performance_id_map = {idx: i + len(personnel_nodes) for i, idx in enumerate(performance_nodes)}
genre_id_map = {genre: i + len(personnel_nodes) + len(performance_nodes) for i, genre in enumerate(genre_nodes)}

print("\n노드 ID 매핑 생성 완료.")
# print("인물/기관 ID 예시:", list(personnel_id_map.items())[:5])
# print("공연 ID 예시:", list(performance_id_map.items())[:5])
# print("장르 ID 예시:", list(genre_id_map.items())[:5])


# 2. 그래프 엣지 데이터 구축

# 참여 엣지(Participation Edge): 공연-인물/기관 연결
# df와 df_complex의 각 행을 순회하며 엣지를 기록합니다.
participation_edges = []

# df 데이터프레임 처리
for index, row in df.iterrows():
    performance_id = performance_id_map[index]
    for person_name in row['출연진내용_standardized']:
        if person_name in personnel_id_map: # 표준화 과정에서 빈 문자열이 남았을 경우 제외
             person_id = personnel_id_map[person_name]
             participation_edges.append((performance_id, person_id)) # (공연 노드 ID, 인물/기관 노드 ID) 엣지 추가

# df_complex 데이터프레임 처리
for index, row in df_complex.iterrows():
    performance_id = performance_id_map[index]
    for person_name in row['출연진내용_standardized']:
        if person_name in personnel_id_map:
            person_id = personnel_id_map[person_name]
            participation_edges.append((performance_id, person_id))

    for person_name in row['제작진내용_standardized']:
         if person_name in personnel_id_map:
            person_id = personnel_id_map[person_name]
            participation_edges.append((performance_id, person_id))


# 중복 엣지 제거 (하나의 인물/기관이 한 공연에 여러 역할로 참여해도 엣지는 하나만 필요)
participation_edges = list(set(participation_edges))

print(f"\n총 참여 엣지 수: {len(participation_edges)}")
# print("참여 엣지 예시:", participation_edges[:10])

# 엣지 데이터를 DataFrame으로 변환 (선택 사항이지만 관리가 용이)
participation_edges_df = pd.DataFrame(participation_edges, columns=['source', 'target'])
print("\n참여 엣지 데이터프레임 생성 완료.")
display(participation_edges_df.head())

총 인물/기관 노드 수: 38786
총 공연 노드 수: 74512
총 장르 노드 수: 8
장르 노드 리스트: ['대중무용', '대중음악', '무용(서양/한국무용)', '뮤지컬', '서양음악(클래식)', '서커스/마술', '연극', '한국음악(국악)']

노드 ID 매핑 생성 완료.

총 참여 엣지 수: 229560

참여 엣지 데이터프레임 생성 완료.

   source  target
0   41217    7196
1   40090    5994
2   86928   30315
3   85875   25844
4   57578   34813

In [18]:
# 모델을 평가 모드로 설정
model.eval()

# 그래디언트 계산 비활성화 (메모리 사용량 감소 및 속도 향상)
with torch.no_grad():
    # 전체 그래프에 대해 모델 예측 수행
    out = model(data.x, data.edge_index)

    # 복합 장르 공연 노드에 해당하는 출력만 가져오기
    performance_output = out[len(personnel_nodes) : len(personnel_nodes) + len(performance_nodes)]
    complex_performances_output = performance_output[data.predict_mask]

    # 예측 결과 (가장 높은 확률을 가지는 장르의 인덱스) 가져오기
    # 변경: 상위 2개 장르의 확률과 인덱스를 가져오기
    top2_probs, top2_genres_indices = torch.topk(complex_performances_output, k=2, dim=1)

# 예측된 장르 인덱스를 실제 장르명으로 변환
index_to_genre_map = {i: genre for genre, i in genre_class_map.items()}

# 상위 2개 장르명을 리스트로 저장
predicted_top2_genres = []
for indices in top2_genres_indices:
    predicted_top2_genres.append([index_to_genre_map[idx.item()] for idx in indices])

# 복합 장르 공연의 원래 인덱스 가져오기 (이전 셀에서 사용한 로직 재활용)
complex_performance_original_indices_aligned = []
for original_idx in df_complex.index:
    performance_graph_id_full = performance_id_map[original_idx]
    performance_graph_id_relative = performance_graph_id_full - len(personnel_nodes)
    if data.predict_mask[performance_graph_id_relative]:
        complex_performance_original_indices_aligned.append(original_idx)


# 예측 결과를 DataFrame으로 정리
predictions_df = pd.DataFrame({
    'Original_Index_df_complex': complex_performance_original_indices_aligned,
    'Predicted_Top_2_Genres': predicted_top2_genres,
    'Predicted_Top_2_Probabilities': top2_probs.tolist() # 확률도 함께 저장 (선택 사항)
})

print("복합 장르 공연 상위 2개 예측 결과:")
display(predictions_df.head())

# 예측 결과 예시 출력 (원본 데이터와 함께 비교)
print("\n원본 데이터 (df_complex)와 예측 결과 비교 예시:")
display(df_complex.loc[predictions_df['Original_Index_df_complex'].head()][['공연명', '장르명', '세부장르명']].merge(predictions_df.head(), left_index=True, right_on='Original_Index_df_complex'))

복합 장르 공연 상위 2개 예측 결과:

,Original_Index_df_complex,Predicted_Top_2_Genres,Predicted_Top_2_Probabilities
0,0,"[뮤지컬, 연극]","[-3.766942609217949e-05, -11.247454643249512]"
1,1,"[뮤지컬, 연극]","[-3.099393507000059e-05, -11.345272064208984]"
2,2,"[대중음악, 연극]","[-5.817244164063595e-05, -10.747735977172852]"
3,3,"[대중음악, 연극]","[-0.9334772229194641, -1.318832278251648]"
4,4,"[뮤지컬, 대중음악]","[-4.827859811484814e-05, -10.738018989562988]"

원본 데이터 (df_complex)와 예측 결과 비교 예시:

,공연명,장르명,세부장르명,Original_Index_df_complex,Predicted_Top_2_Genres,Predicted_Top_2_Probabilities
0,인더스트리얼 퍼포먼스,복합,다원/융복합,0,"[뮤지컬, 연극]","[-3.766942609217949e-05, -11.247454643249512]"
1,아웃 오브 더 블루,복합,복합,1,"[뮤지컬, 연극]","[-3.099393507000059e-05, -11.345272064208984]"
2,이색콘서트,복합,복합,2,"[대중음악, 연극]","[-5.817244164063595e-05, -10.747735977172852]"
3,슬픔의 집,복합,다원/융복합,3,"[대중음악, 연극]","[-0.9334772229194641, -1.318832278251648]"
4,"차세대열전, 이어지음 프로젝트",복합,복합,4,"[뮤지컬, 대중음악]","[-4.827859811484814e-05, -10.738018989562988]"

In [11]:
# 2. 계속: 그래프 엣지 데이터 구축

# 장르 엣지(Genre Edge): 공연-장르 연결 (학습용)
# 단일 장르 공연 데이터프레임인 df에 대해서만 수행합니다.
genre_edges = []
# GNN 모델 학습을 위한 라벨 데이터 (정답)
genre_labels = {}

for index, row in df.iterrows():
    performance_id = performance_id_map[index]
    genre_name = row['장르명']
    # '대중음악'처럼 장르명에 괄호가 포함된 경우를 대비하여 통일
    # 예: '국악(국악)' -> '국악'
    clean_genre_name = genre_name.split('(')[0]

    # 엣지 추가
    if clean_genre_name in genre_id_map:
        genre_id = genre_id_map[clean_genre_name]
        genre_edges.append((performance_id, genre_id))

    # 라벨 데이터 저장
    # GNN은 보통 정수 라벨을 사용하므로, 장르명 대신 ID를 사용
    genre_labels[performance_id] = genre_id_map[genre_name]


# 중복 엣지 제거
genre_edges = list(set(genre_edges))

print(f"\n총 장르 엣지 수: {len(genre_edges)}")
# print("장르 엣지 예시:", genre_edges[:10])

# 엣지 데이터를 DataFrame으로 변환
genre_edges_df = pd.DataFrame(genre_edges, columns=['source', 'target'])
print("\n장르 엣지 데이터프레임 생성 완료.")
display(genre_edges_df.head())

# 모든 엣지 통합
# participation_edges_df와 genre_edges_df를 결합하여 최종 엣지 리스트 생성
all_edges_df = pd.concat([participation_edges_df, genre_edges_df], ignore_index=True)
print(f"\n총 통합 엣지 수: {len(all_edges_df)}")
display(all_edges_df.head())

# 최종 그래프 구축 준비 완료
print("\n그래프 데이터셋 구축을 위한 모든 엣지 데이터가 준비되었습니다.")
print("다음 단계는 이 데이터를 PyTorch Geometric 또는 DGL 형식으로 변환하여 GNN 모델을 학습시키는 것입니다.")

총 장르 엣지 수: 36613

장르 엣지 데이터프레임 생성 완료.

   source  target
0   46308  113301
1   75785  113304
2   43097  113304
3   75523  113304
4   43231  113304

총 통합 엣지 수: 266173

   source  target
0   41217    7196
1   40090    5994
2   86928   30315
3   85875   25844
4   57578   34813

그래프 데이터셋 구축을 위한 모든 엣지 데이터가 준비되었습니다.
다음 단계는 이 데이터를 PyTorch Geometric 또는 DGL 형식으로 변환하여 GNN 모델을 학습시키는 것입니다.

In [19]:
# df_complex와 예측 결과를 병합하여 새로운 데이터프레임 생성
# predictions_df의 'Original_Index_df_complex' 컬럼을 기준으로 df_complex와 병합합니다.
# merge 함수는 기본적으로 인덱스를 기준으로 병합하지 않으므로,
# df_complex의 인덱스를 컬럼으로 만들고 merge를 수행하거나,
# merge의 left_index=True, right_on='Original_Index_df_complex' 옵션을 사용합니다.
# 여기서는 마지막 예측 결과 셀에서 사용한 merge 방식을 따르겠습니다.

# df_complex에 예측 결과를 병합 (Original_Index_df_complex 컬럼을 기준으로)
df_complex_with_predictions = df_complex.merge(
    predictions_df,
    left_index=True,
    right_on='Original_Index_df_complex'
)

# 병합 후 'Original_Index_df_complex' 컬럼은 필요 없으므로 삭제할 수 있습니다.
# df_complex_with_predictions = df_complex_with_predictions.drop(columns=['Original_Index_df_complex'])

# 결과 확인
print("복합 장르 공연 원본 데이터와 상위 2개 예측 장르 포함 테이블:")
display(df_complex_with_predictions.head())

# 필요한 경우, 예측된 장르 조합을 하나의 문자열 컬럼으로 만들 수도 있습니다.
df_complex_with_predictions['Predicted_Genre_Combination'] = df_complex_with_predictions['Predicted_Top_2_Genres'].apply(lambda x: ' + '.join(x))

print("\n예측 장르 조합 컬럼 추가 결과:")
display(df_complex_with_predictions[['공연명', '장르명', '세부장르명', 'Predicted_Top_2_Genres', 'Predicted_Genre_Combination']].head())

복합 장르 공연 원본 데이터와 상위 2개 예측 장르 포함 테이블:

,공연명,장르명,세부장르명,출연진내용,제작진내용,기획제작사명,원작자명,극작가명,출연진내용_list,제작진내용_list,출연진내용_standardized,제작진내용_standardized,Original_Index_df_complex,Predicted_Top_2_Genres,Predicted_Top_2_Probabilities
0,인더스트리얼 퍼포먼스,복합,다원/융복합,"예효승, 나혜영",NaN,금은보화(주관),NaN,NaN,"[예효승, 나혜영]",[],"[예효승, 나혜영]",[],0,"[뮤지컬, 연극]","[-3.766942609217949e-05, -11.247454643249512]"
1,아웃 오브 더 블루,복합,복합,"신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등",류경한,"SY Ent(에스와이 이엔티)(주관), 김지연 아코디언 팝스오케스트라(주최)",NaN,NaN,"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한],"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한],1,"[뮤지컬, 연극]","[-3.099393507000059e-05, -11.345272064208984]"
2,이색콘서트,복합,복합,김진철,NaN,"(주)지앤미디어(주최), (주)지앤미디어(기획사)",NaN,NaN,[김진철],[],[김진철],[],2,"[대중음악, 연극]","[-5.817244164063595e-05, -10.747735977172852]"
3,슬픔의 집,복합,다원/융복합,NaN,"김지선, 강윤지, 문기강 등",NaN,NaN,NaN,[],"[김지선, 강윤지, 문기강]",[],"[김지선, 강윤지, 문기강]",3,"[대중음악, 연극]","[-0.9334772229194641, -1.318832278251648]"
4,"차세대열전, 이어지음 프로젝트",복합,복합,"강인아, 고석진, 조의선, 최태훈","강안나, 강한별, 최세린 등",한국문화예술위원회(주최),NaN,NaN,"[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]","[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]",4,"[뮤지컬, 대중음악]","[-4.827859811484814e-05, -10.738018989562988]"

예측 장르 조합 컬럼 추가 결과:

,공연명,장르명,세부장르명,Predicted_Top_2_Genres,Predicted_Genre_Combination
0,인더스트리얼 퍼포먼스,복합,다원/융복합,"[뮤지컬, 연극]",뮤지컬 + 연극
1,아웃 오브 더 블루,복합,복합,"[뮤지컬, 연극]",뮤지컬 + 연극
2,이색콘서트,복합,복합,"[대중음악, 연극]",대중음악 + 연극
3,슬픔의 집,복합,다원/융복합,"[대중음악, 연극]",대중음악 + 연극
4,"차세대열전, 이어지음 프로젝트",복합,복합,"[뮤지컬, 대중음악]",뮤지컬 + 대중음악

In [12]:
# # PyTorch Geometric 설치
# %pip install torch torch_geometric

import torch
from torch_geometric.data import Data

In [13]:
# 노드 피처 생성 (간단하게 모든 노드를 원-핫 인코딩처럼 표현)
# 실제 GNN에서는 더 의미있는 피처를 사용할 수 있습니다.
num_nodes = len(personnel_nodes) + len(performance_nodes) + len(genre_nodes)
# 모든 노드에 대한 단위 행렬을 피처로 사용 (가장 기본적인 형태)
x = torch.eye(num_nodes)

# 엣지 데이터 준비
# all_edges_df는 source, target 컬럼을 가진 DataFrame
# PyTorch Geometric은 엣지를 [2, num_edges] 형태의 텐서로 기대합니다.
# 첫 번째 행은 source 노드 인덱스, 두 번째 행은 target 노드 인덱스
edge_index = torch.tensor(all_edges_df.values.T, dtype=torch.long)


# 라벨 데이터 준비 (단일 장르 공연에 대한 라벨만 사용)
# PyTorch Geometric의 Data 객체는 노드 순서대로 라벨을 가집니다.
# 우리는 df의 index를 performance_id로 사용했고, 이는 performance_id_map에 매핑되어 있습니다.
# 학습에 사용할 공연 노드 (단일 장르 공연)의 ID와 해당 라벨을 매핑해야 합니다.

# 모든 공연 노드에 대한 초기 라벨을 -1 등으로 설정 (라벨이 없는 노드)
y = torch.full((len(performance_nodes),), fill_value=-1, dtype=torch.long) # 공연 노드 수 만큼 라벨 텐서 생성


# genre_labels 딕셔너리의 키를 df의 원래 인덱스로 사용
genre_labels = {}
# 장르명에 대한 클래스 인덱스 매핑 (0부터 len(genre_nodes)-1)
genre_class_map = {genre: i for i, genre in enumerate(genre_nodes)}

for index, row in df.iterrows():
    genre_name = row['장르명']
    # '대중음악'처럼 장르명에 괄호가 포함된 경우를 대비하여 통일
    clean_genre_name = genre_name.split('(')[0]

    if clean_genre_name in genre_class_map: # 변경: genre_id_map 대신 genre_class_map 사용
         # 변경: 장르 ID 대신 클래스 인덱스를 사용
         genre_class_index = genre_class_map[clean_genre_name]
         genre_labels[index] = genre_class_index # df의 원래 인덱스를 키로 사용, 클래스 인덱스를 값으로 저장


# 단일 장르 공연의 실제 라벨 채우기
for original_index, genre_class_index in genre_labels.items(): # 변경: genre_id 대신 genre_class_index 사용
    # original_index는 df의 인덱스입니다.
    # performance_id_map에서 해당 df 인덱스에 해당하는 전체 그래프 노드 ID를 찾습니다.
    performance_graph_id_full = performance_id_map[original_index]
    # y 텐서는 공연 노드만을 대상으로 하므로, 공연 노드의 0부터 시작하는 인덱스를 계산합니다.
    performance_graph_id_relative = performance_graph_id_full - len(personnel_nodes)
    y[performance_graph_id_relative] = genre_class_index # 변경: 장르 ID 대신 클래스 인덱스 저장


# GNN 학습은 라벨이 있는 단일 장르 공연 노드에 대해서만 수행
# 학습 마스크 생성: 라벨이 -1이 아닌 공연 노드만 True
train_mask = (y != -1)

# 복합 장르 공연 노드에 대한 마스크 생성 (예측 대상) - 기존 코드 유지
predict_mask = torch.zeros(len(performance_nodes), dtype=torch.bool)
for original_index in df_complex.index:
    performance_graph_id_full = performance_id_map[original_index]
    performance_graph_id_relative = performance_graph_id_full - len(personnel_nodes)
    predict_mask[performance_graph_id_relative] = True


# PyTorch Geometric Data 객체 생성
# x: Node features [num_nodes, num_node_features]
# edge_index: Graph connectivity in COO format with shape [2, num_edges]
# y: Node labels [num_nodes] - 여기서는 공연 노드에 대한 라벨만 (y 텐서의 크기는 공연 노드 수)
# train_mask: Mask for training nodes [num_nodes] - 여기서는 공연 노드에 대한 마스크 (train_mask의 크기는 공연 노드 수)

data = Data(x=x, edge_index=edge_index, y=y, train_mask=train_mask)

# Data 객체 확인
print("\nPyTorch Geometric Data 객체 생성 완료:")
print(data)
print(f"Number of nodes: {data.num_nodes}")
print(f"Number of edges: {data.num_edges}")
print(f"Number of training nodes (performances): {data.train_mask.sum()}")
print(f"Number of nodes with labels: {(data.y != -1).sum()}") # 라벨이 -1이 아닌 노드 수 (단일 장르 공연)

# 복합 장르 예측을 위한 마스크는 따로 저장
data.predict_mask = predict_mask
print(f"Number of prediction nodes (complex performances): {data.predict_mask.sum()}")

PyTorch Geometric Data 객체 생성 완료:
Data(x=[113306, 113306], edge_index=[2, 266173], y=[74512], train_mask=[74512])
Number of nodes: 113306
Number of edges: 266173
Number of training nodes (performances): 36613
Number of nodes with labels: 36613
Number of prediction nodes (complex performances): 1421

In [14]:
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

# 모델 초기화
# data.num_node_features는 현재 113306 (원-핫 인코딩 피처 차원)
# 출력 채널 수는 장르 노드의 수 (8개)
model = GCN(in_channels=data.num_node_features, hidden_channels=64, out_channels=len(genre_nodes))

print("GCN 모델 정의 완료:")
print(model)

GCN 모델 정의 완료:
GCN(
  (conv1): GCNConv(113306, 64)
  (conv2): GCNConv(64, 8)
)

In [15]:
import torch.optim as optim

# 옵티마이저 설정
# Adam 옵티마이저를 사용하며, 모델의 모든 파라미터를 최적화 대상으로 합니다.
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 손실 함수 설정
# log_softmax 출력을 사용하므로 Negative Log Likelihood 손실 함수를 사용합니다.
criterion = nn.NLLLoss()

# 모델을 학습 모드로 설정
model.train()

# 학습 루프
epochs = 200 # 학습 횟수 설정 (필요에 따라 조정 가능)

for epoch in range(epochs):
    optimizer.zero_grad() # 그래디언트 초기화
    out = model(data.x, data.edge_index) # 모델 예측 수행

    # 학습 데이터에 해당하는 노드의 출력과 라벨만 사용하여 손실 계산
    # data.y는 공연 노드에 대한 라벨 텐서이고, train_mask는 학습에 사용할 공연 노드를 나타냅니다.
    # out 텐서의 크기는 전체 노드 수 x 장르 수 입니다.
    # 우리는 공연 노드 (personnel_nodes 수 이후부터)에 대한 출력만 필요합니다.
    # train_mask는 공연 노드 텐서 (y 텐서와 같은 크기)에 대한 마스크입니다.
    # 따라서 전체 출력(out)에서 공연 노드에 해당하는 부분만 슬라이싱한 후, train_mask를 적용합니다.

    performance_output = out[len(personnel_nodes) : len(personnel_nodes) + len(performance_nodes)]

    # train_mask가 True인 위치의 출력과 라벨에 대해서만 손실 계산
    loss = criterion(performance_output[data.train_mask], data.y[data.train_mask])

    loss.backward() # 역전파
    optimizer.step() # 옵티마이저 스텝

    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

print("\n모델 학습 완료!")

Epoch 10/200, Loss: 1.2988
Epoch 20/200, Loss: 0.4713
Epoch 30/200, Loss: 0.1191
Epoch 40/200, Loss: 0.0397
Epoch 50/200, Loss: 0.0194
Epoch 60/200, Loss: 0.0112
Epoch 70/200, Loss: 0.0075
Epoch 80/200, Loss: 0.0059
Epoch 90/200, Loss: 0.0046
Epoch 100/200, Loss: 0.0039
Epoch 110/200, Loss: 0.0035
Epoch 120/200, Loss: 0.0029
Epoch 130/200, Loss: 0.0027
Epoch 140/200, Loss: 0.0026
Epoch 150/200, Loss: 0.0022
Epoch 160/200, Loss: 0.0021
Epoch 170/200, Loss: 0.0019
Epoch 180/200, Loss: 0.0017
Epoch 190/200, Loss: 0.0016
Epoch 200/200, Loss: 0.0015

모델 학습 완료!

In [20]:
df_complex.head()

,공연명,장르명,세부장르명,출연진내용,제작진내용,기획제작사명,원작자명,극작가명,출연진내용_list,제작진내용_list,출연진내용_standardized,제작진내용_standardized
0,인더스트리얼 퍼포먼스,복합,다원/융복합,"예효승, 나혜영",NaN,금은보화(주관),NaN,NaN,"[예효승, 나혜영]",[],"[예효승, 나혜영]",[]
1,아웃 오브 더 블루,복합,복합,"신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등",류경한,"SY Ent(에스와이 이엔티)(주관), 김지연 아코디언 팝스오케스트라(주최)",NaN,NaN,"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한],"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한]
2,이색콘서트,복합,복합,김진철,NaN,"(주)지앤미디어(주최), (주)지앤미디어(기획사)",NaN,NaN,[김진철],[],[김진철],[]
3,슬픔의 집,복합,다원/융복합,NaN,"김지선, 강윤지, 문기강 등",NaN,NaN,NaN,[],"[김지선, 강윤지, 문기강]",[],"[김지선, 강윤지, 문기강]"
4,"차세대열전, 이어지음 프로젝트",복합,복합,"강인아, 고석진, 조의선, 최태훈","강안나, 강한별, 최세린 등",한국문화예술위원회(주최),NaN,NaN,"[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]","[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]"

In [21]:
df_complex_with_predictions.head()

,공연명,장르명,세부장르명,출연진내용,제작진내용,기획제작사명,원작자명,극작가명,출연진내용_list,제작진내용_list,출연진내용_standardized,제작진내용_standardized,Original_Index_df_complex,Predicted_Top_2_Genres,Predicted_Top_2_Probabilities,Predicted_Genre_Combination
0,인더스트리얼 퍼포먼스,복합,다원/융복합,"예효승, 나혜영",NaN,금은보화(주관),NaN,NaN,"[예효승, 나혜영]",[],"[예효승, 나혜영]",[],0,"[뮤지컬, 연극]","[-3.766942609217949e-05, -11.247454643249512]",뮤지컬 + 연극
1,아웃 오브 더 블루,복합,복합,"신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영 등",류경한,"SY Ent(에스와이 이엔티)(주관), 김지연 아코디언 팝스오케스트라(주최)",NaN,NaN,"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한],"[신유, 김지연, 김대희, 류재경, 김은혜, 정재희, 장보영]",[류경한],1,"[뮤지컬, 연극]","[-3.099393507000059e-05, -11.345272064208984]",뮤지컬 + 연극
2,이색콘서트,복합,복합,김진철,NaN,"(주)지앤미디어(주최), (주)지앤미디어(기획사)",NaN,NaN,[김진철],[],[김진철],[],2,"[대중음악, 연극]","[-5.817244164063595e-05, -10.747735977172852]",대중음악 + 연극
3,슬픔의 집,복합,다원/융복합,NaN,"김지선, 강윤지, 문기강 등",NaN,NaN,NaN,[],"[김지선, 강윤지, 문기강]",[],"[김지선, 강윤지, 문기강]",3,"[대중음악, 연극]","[-0.9334772229194641, -1.318832278251648]",대중음악 + 연극
4,"차세대열전, 이어지음 프로젝트",복합,복합,"강인아, 고석진, 조의선, 최태훈","강안나, 강한별, 최세린 등",한국문화예술위원회(주최),NaN,NaN,"[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]","[강인아, 고석진, 조의선, 최태훈]","[강안나, 강한별, 최세린]",4,"[뮤지컬, 대중음악]","[-4.827859811484814e-05, -10.738018989562988]",뮤지컬 + 대중음악

In [ ]:
df_complex_with_predictions.head()

In [23]:
# df_complex_with_predictions 데이터프레임을 CSV 파일로 저장
# output_path = 'complex_with_predictions.csv' # 현재 작업 디렉토리
output_path = '/content/drive/MyDrive/KOPIS 공모전/data/complex_with_predictions.csv' # Google Drive의 지정된 폴더

df_complex_with_predictions.to_csv(output_path, index=False)

print(f"'{output_path}' 파일로 저장이 완료되었습니다.")

'/content/drive/MyDrive/KOPIS 공모전/data/complex_with_predictions.csv' 파일로 저장이 완료되었습니다.